public class GenerateUserStructureSchedule implements Queueable {
	//public Map<String,Type> mapInitialClassWithSegment = new Map<String,Type>{
	//	'SME'=>SMEUserManagement.class, 
	//	'RBS'=>RBSUserManagement.class, 
	//	'AF'=>AFUserManagement.class
	//};
	public void execute(QueueableContext context) {
        //for(String eachSegment : mapInitialClassWithSegment.keySet()){
        //	Type segmentClassType = mapInitialClassWithSegment.get(eachSegment);
        //	IUserManagement segmentClass = (IUserManagement)segmentClassType.newInstance();
        //	Database.executeBatch(new UserStructure_Batch(segmentClass));
        //}
	}
}