<!DOCTYPE html>
<html>
  <body style="margin:0; font-family:Arial Unicode MS !important; font-size:12px;" >

  <p>

<img  src="/resource/Doc_LG_TH_V4_Image/Doc_LG_TH_V4_0.jpg" style="top:0px; left: 0px; width: 794px;" height="1122"/></p>
&nbsp;<span class="elementValue" style="left: 285px; top: 152px; width: 335px; height: 17px; text-align:left">{!Name_Surname_TH__c}</span>
<span class="elementValue" style="left: 285px; top: 178px; width: 336px; height: 20px; text-align:left; right: 173px;">{!Name_Surname_EN__c}</span>
<span class="elementValue" style="left:302px; top:201px; width:247px; height: 18px; text-align:left">{!Encrypt_Identification_No__c}</span>

  <div  style="page-break-after: true;"/>

      	  	  
<img  src="/resource/Doc_LG_TH_V4_Image/Doc_LG_TH_V4_1.gif" style="top:1122px; width: 794px; left: 0px;"/>&nbsp;
    
    <div  style="page-break-after: true;"/>
      
   
<img  src="/resource/Doc_LG_TH_V4_Image/Doc_LG_TH_V4_2.gif" style="top:2244px; width: 794px;"/>&nbsp;

  <div  style="page-break-after: true;"/>
  
  
<img  src="/resource/Doc_LG_TH_V4_Image/Doc_LG_TH_V4_3.gif" style="top:3366px; width: 794px;"/>   
<span class="elementValue" style="left:299px; top:4261px; width:350px; height: 16px; text-align:left">{!Owner_Name__c}</span>
<span class="elementValue" style="left:158px; top:4283px; width:141px; height: 16px; text-align:left">{!owner.MobilePhone}</span>
<span class="elementValue" style="left:398px; top:4242px; width:94px; height: 16px; text-align:left">{!CIS__c}</span>
<span class="elementValue" style="left:156px; top:4263px; width:94px; height: 16px; text-align:left">{!OWNER_EMP_ID__C}</span>
  
  <div  style="page-break-after: true;"/>

<img  src="/resource/Doc_LG_TH_V4_Image/Doc_LG_TH_V4_4.gif" style="top:4488px; width: 794px;"/>

  <div  style="page-break-after: true;"/>

<img  src="/resource/Doc_LG_TH_V4_Image/Doc_LG_TH_V4_5.gif" style="top:5610px; width: 794px;"/>

  <div  style="page-break-after: true;"/>

<img  src="/resource/Doc_LG_TH_V4_Image/Doc_LG_TH_V4_6.gif" style="top:6732px; width: 794px;"/>

  <div  style="page-break-after: true;"/>

<img  src="/resource/Doc_LG_TH_V4_Image/Doc_LG_TH_V4_7.gif" style="top:7854px; width: 794px;"/>

  <div  style="page-break-after: true;"/>
  
<img  src="/resource/Doc_LG_TH_V4_Image/Doc_LG_TH_V4_8.gif" style="top:8976px; width: 794px;"/>

  <div  style="page-break-after: true;"/>

  
<img  src="/resource/Doc_LG_TH_V4_Image/Doc_LG_TH_V4_9.gif" style="top:10098px; width: 794px;"/>

  <div  style="page-break-after: true;"/>

  
<img  src="/resource/Doc_LG_TH_V4_Image/Doc_LG_TH_V4_10.gif" style="top:11220px; width: 794px;"/>

  <div  style="page-break-after: true;"/>

  
<img  src="/resource/Doc_LG_TH_V4_Image/Doc_LG_TH_V4_11.gif" style="top:12342px; width: 794px;"/>

  <div  style="page-break-after: true;"/>

  
<img  src="/resource/Doc_LG_TH_V4_Image/Doc_LG_TH_V4_12.gif" style="top:13464px; width: 794px;"/>

  <div  style="page-break-after: true;"/>

  
<img  src="/resource/Doc_LG_TH_V4_Image/Doc_LG_TH_V4_13.gif" style="top:14586px; width: 794px;"/>

  <div  style="page-break-after: true;"/>

  
<img  src="/resource/Doc_LG_TH_V4_Image/Doc_LG_TH_V4_14.gif" style="top:15708px; width: 794px;"/>

  <div  style="page-break-after: true;"/>

  
<img  src="/resource/Doc_LG_TH_V4_Image/Doc_LG_TH_V4_15.gif" style="top:16830px; width: 794px;"/>

  <div  style="page-break-after: true;"/>

  
<img  src="/resource/Doc_LG_TH_V4_Image/Doc_LG_TH_V4_16.gif" style="top:17952px; width: 794px;"/>

  <div  style="page-break-after: true;"/>

  
<img  src="/resource/Doc_LG_TH_V4_Image/Doc_LG_TH_V4_17.gif" style="top:19074px; width: 794px;"/>

  <div  style="page-break-after: true;"/>

  
<img  src="/resource/Doc_LG_TH_V4_Image/Doc_LG_TH_V4_18.gif" style="top:20196px; width: 794px;"/>

  <div  style="page-break-after: true;"/>
		
	</body>
</html>
