<!DOCTYPE html>
<html>
  <body style="margin:0; font-family:Arial Unicode MS !important; font-size:12px;" >

  <p>

<img  src="/resource/Doc_SOL_SignatureCard_MT_Image/Doc_SOL_SignatureCard_MT_0.jpg" style="top:0px; left: 0px; width: 794px;" height="1122"/></p>
&nbsp;<span class="elementValue" style="left: 262px; top: 210px; width: 335px; height: 17px; text-align:left">{!Name_Surname_TH__c}</span>
<span class="elementValue" style="left: 262px; top: 237px; width: 266px; height: 20px; text-align:left">{!Name_Surname_EN__c}</span>
<span class="elementValue" style="left:340px; top:258px; width:247px; height: 18px; text-align:left">{!Encrypt_Identification_No__c}</span>
<span class="elementValue" style="left:88px; top:966px; width:177px; height: 16px; text-align:left">{!Owner_Name__c}</span>
<span class="elementValue" style="left:548px; top:966px; width:216px; height: 16px; text-align:left">{!owner.Email}</span>
<span class="elementValue" style="left:369px; top:966px; width:105px; height: 16px; text-align:left">{!owner.MobilePhone}</span>

  <div  style="page-break-after: true;"/>

      	  	  
<img  src="/resource/Doc_SOL_SignatureCard_MT_Image/Doc_SOL_SignatureCard_MT_1.jpg" style="top:1122px; width: 794px; left: 0px;"/>&nbsp;
<span class="elementValue" style="left: 277px; top: 1897px; width: 236px; height: 20px; text-align: left">{!Name_Surname_TH__c}</span>
<span class="elementValue" style="left: 277px; top: 1923px; width: 335px; height: 20px; text-align:left">{!Name_Surname_EN__c}</span>

    
    <div  style="page-break-after: true;"/>
      
   
<img  src="/resource/Doc_SOL_SignatureCard_MT_Image/Doc_SOL_SignatureCard_MT_2.jpg" style="top:2244px; width: 794px;"/>&nbsp;
<span class="elementValue" style="left: 245px; top: 2416px; width: 341px; height: 16px; text-align: left">{!Name_Surname_TH__c}</span>
<span class="elementValue" style="left: 245px; top: 2442px; width: 335px; height: 20px; text-align:left">{!Name_Surname_EN__c}</span>

  <div  style="page-break-after: true;"/>
  
  
<img  src="/resource/Doc_SOL_SignatureCard_MT_Image/Doc_SOL_SignatureCard_MT_3.jpg" style="top:3366px; width: 794px;"/>   
<span class="elementValue" style="left: 247px; top: 3530px; width: 341px; height: 16px; text-align: left">{!Name_Surname_TH__c}</span>
<span class="elementValue" style="left: 247px; top: 3555px; width: 335px; height: 20px; text-align:left">{!Name_Surname_EN__c}</span>
     

  <div  style="page-break-after: true;"/>

<img  src="/resource/Doc_SOL_SignatureCard_MT_Image/Doc_SOL_SignatureCard_MT_4.jpg" style="top:4488px; width: 794px;"/>
<span class="elementValue" style="left: 241px; top: 4645px; width: 341px; height: 16px; text-align: left">{!Name_Surname_TH__c}</span>
<span class="elementValue" style="left: 241px; top: 4676px; width: 335px; height: 20px; text-align: left">{!Name_Surname_EN__c}</span>
        

  <div  style="page-break-after: true;"/>

		</body>
	</html>
