<!DOCTYPE html>
<html>
  <body style="margin:0; font-family:Arial Unicode MS !important; font-size:12px;" >

<img  src="/resource/Doc_CDD_KeDoc_V2_Image/Doc_CDD_KeDoc_V2_0.jpg" style="top:0px; left: 0px; width: 794px;" height="1122"/>
&nbsp;<span class="elementValue" style="left: 220px; top: 182px; width: 335px; height: 17px; text-align:left">{!Name_Surname_TH__c}</span>
<span class="elementValue" style="left:355px; top:212px; width:247px; height: 18px; text-align:left">{!Encrypt_Identification_No__c}</span>
<span class="elementValue" style="left:161px; top:237px; width:216px; height: 16px; text-align:left">{!email_encrypted__c}</span>
<span class="elementValue" style="left:681px; top:151px; width:57px; height: 16px; font-size:7px; text-align:left">{!CIS__c}</span>

  <div  style="page-break-after: true;"/>

      	  	  
<img  src="/resource/Doc_CDD_KeDoc_V2_Image/Doc_CDD_KeDoc_V2_2.jpg" style="top:1122px; width: 794px; left: 0px;"/>&nbsp;
    
    <div  style="page-break-after: true;"/>
      
   
<img  src="/resource/Doc_CDD_KeDoc_V2_Image/Doc_CDD_KeDoc_V2_3.jpg" style="top:2244px; width: 794px;"/>&nbsp;

  <div  style="page-break-after: true;"/>
  
  
<img  src="/resource/Doc_CDD_KeDoc_V2_Image/Doc_CDD_KeDoc_V2_4.jpg" style="top:3366px; width: 794px;"/>   
   
  <div  style="page-break-after: true;"/>

<img  src="/resource/Doc_CDD_KeDoc_V2_Image/Doc_CDD_KeDoc_V2_5.jpg" style="top:4488px; width: 794px;"/>
       
  <div  style="page-break-after: true;"/>

<img  src="/resource/Doc_CDD_KeDoc_V2_Image/Doc_CDD_KeDoc_V2_6.jpg" style="top:5610px; width: 794px;"/>
      
  <div  style="page-break-after: true;"/>

  </body>
