<!DOCTYPE html>


  <body style="margin:0; font-family:Arial Unicode MS !important; font-size:12px;" >

<img  src="/resource/Doc_KPLUS_SME_OJoin_EN_Image/Doc_KPLUS_SME_OJoin_EN_01.jpg" style="top:0px; left: 0px; width: 794px;" height="1122"/>    

  <div  style="page-break-after: true;"/>

      	  	  
<img  src="/resource/Doc_KPLUS_SME_OJoin_EN_Image/Doc_KPLUS_SME_OJoin_EN_02.jpg" style="top:1122px; width: 794px; left: 0px;"/>
    
    <div  style="page-break-after: true;"/>
      

  </body>
  